# Generated by Django 6.1.1 on 2026-09-14 13:36

import products.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_pg_textsearch"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=products.indexes.BM25Index(
                fields=["search_field"],
                name="products_search_idx",
                text_config="english",
            ),
        ),
    ]
