# Generated by Django 6.1.1 on 2026-09-14 13:37

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_pgvector"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=pgvector.django.indexes.HnswIndex(
                fields=["embedding"],
                name="products_embedding_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
